#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

echo "Enabling Istio"

if [ ! -f "${SNAP_DATA}/bin/istioctl" ]
then
  ISTIO_VERSION="1.19.3"
  echo "Fetching istioctl version $ISTIO_VERSION."
  ISTIO_ERSION=$(echo $ISTIO_VERSION | sed 's/v//g')
  run_with_sudo mkdir -p "${SNAP_DATA}/tmp/istio-src"
  (cd "${SNAP_DATA}/tmp/istio-src"
  fetch_as https://github.com/istio/istio/archive/refs/tags/$ISTIO_VERSION.tar.gz "$SNAP_DATA/tmp/istio-src/istio-src.tar.gz"
  run_with_sudo gzip -q -d "$SNAP_DATA/tmp/istio-src/istio-src.tar.gz"
  run_with_sudo tar -xvf "$SNAP_DATA/tmp/istio-src/istio-src.tar")
  run_with_sudo mkdir -p "$SNAP_DATA/bin/"
  go build -C "$SNAP_DATA/tmp/istio-src/istio-${ISTIO_ERSION}/istioctl/cmd/istioctl/" -o "$SNAP_DATA/bin/istioctl"
  # run_with_sudo mv "$SNAP_DATA/tmp/istio-src/istio-${ISTIO_ERSION}/istioctl/cmd/istioctl/bin/" "$SNAP_DATA/bin/"
  run_with_sudo chmod +x "$SNAP_DATA/bin/"

  run_with_sudo rm -rf "$SNAP_DATA/tmp/istio-src"
fi

# pod/servicegraph will start failing without dns
"$SNAP/microk8s-enable.wrapper" dns

run_with_sudo "$SNAP_DATA/bin/istioctl" -c "${SNAP_DATA}/credentials/client.config" install --set profile=demo -y

run_with_sudo touch "$SNAP_USER_COMMON/istio.lock"

echo "Istio is starting..."
echo ""
echo "To configure mutual TLS authentication consult the Istio documentation."
